### ISSUE TITLE
Create a slide deck for the start of the meetings

### ISSUE THREAD

**Issue by mattdsteele** [OJUG/OJUG#1]
Let's try Google Docs - we can loop the deck using this approach: https://www.youtube.com/watch?v=Fw8iYv2ERts

What do we want to actually show?
- Social Media (@omahajug account, Meetup info)
- Sponsors
- Other stuff?

**Comment by payne** [comment]
Just shared the draft with all and updated the notes from Friday's lunch.

Still need to add the social media things Matt Steele suggests

**Comment by payne** [comment]
Added a link to twitter upfront.   And speaker ideas.   I'm not good at google slides.

**Comment by jeffsheets** [comment]
Thanks Matts!

I made a few improvements too. Looking good
