### ISSUE TITLE
Please post upcoming meetings?

### ISSUE THREAD

**Issue by payne** [OJUG/OJUG#13]
I suggest this be some sort of rotating task amongst X people so all can be comfortable with the mechanics.   

Right now the September and October meetings need to be posted to both meetup.com and OJUG.org (WordPress Site).

If you'd like to be a user with posting privs on OJUG.org, I can create or (I assume) modify your account.   I assume Jeff can too... 

Ross mentioned to me yesterday that the upcoming meetings were not posted.

Of course, if you don't want to engage in this posting joy -- just tell me and I'm happy to do it.

Thanks

**Comment by mattdsteele** [comment]
Yeah, this is a good idea. Also related to #3.

More generally we discussed rotating leadership duties, or having a "term limit" on responsibilities - I'll create a separate ticket to get that started.

**Comment by payne** [comment]
Right now the September and October meetings need to be posted to both meetup.com and OJUG.org (WordPress Site).

**Comment by jeffsheets** [comment]
I'll try to get things posted and setup for September today. Then let's test our accounts and have someone else try for October?

I'll also try to respond to the other issues soon too…

**Comment by payne** [comment]
Thanks!    no rush

**Comment by jeffsheets** [comment]
new plan. @mattdsteele is going to test out our accounts this month and get things posted for September. I added him as an admin on the ojug.org wordpress site too.

**Comment by payne** [comment]
This is GREAT!    Thanks!!

On Thu, Aug 27, 2015 at 11:24 AM, Jeff Sheets notifications@github.com
wrote:

> new plan. @mattdsteele https://github.com/mattdsteele is going to test
> out our accounts this month and get things posted for September. I added
> him as an admin on the ojug.org wordpress site too.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OJUG/OJUG/issues/13#issuecomment-135514015.

## 

--Matt Payne

**Comment by mattdsteele** [comment]
September has been posted:
- http://www.meetup.com/omahajava/events/225031603/
- http://ojug.org/september-15-intellij-vs-eclipse-showdown/

Closing; we can create a new one for October once we know what we're doing there!
