### ISSUE TITLE
Writeup a list of potential topics

### ISSUE THREAD

**Issue by mattdsteele** [OJUG/OJUG#4]
Similar to what [NebraskaJS has here](https://github.com/NebraskaJS/Wiki/wiki/Speaker-Backlog).

We could point folks toward it who are interested in presenting, but don't know about what yet.

A few things on my list I'd love to see:
- Ratpack framework
- Grails (introduction)
- Groovy/Scala in a Java 8 world
- Deploying Java apps into containers (Docker, etc)
- [Facebook Infer](http://fbinfer.com/)
- [exercism.io](http://exercism.io/) - pair programming/workshop?

@OJUG/owners - feel free to contribute ideas!

**Comment by jeffsheets** [comment]
Love it. And let's add some of these to our pre-meeting slideshow!

**Comment by payne** [comment]
- Elastic Search
- Remote Debugging tomcat/jboss lighting talk
- Any lighting talk based on [spring guides](https://spring.io/guides)

**Comment by javazquez** [comment]
Ill volunteer for ratpack(lightning talk) or anything groovy/clojure
related. I hope to dig into frege and maybe be able to do a talk early
2016. I am also looking at Java performance with provided Java utils and
trying to put a talk together around that.
 Groovy and grails stuff I can pull together quickly if needed :D

A general functional programming on the jvm comparing groovy,clojure and
latest Java 8 is something I have thinking about.

My wish list would be
- Apache Kafka
- Apache samza
- spring project reactor
  -more Rx Java talks
  -prolog on the jvm

Thanks
-Juan

On Sunday, August 16, 2015, Matt Payne notifications@github.com wrote:

> - Elastic Search
> - Remote Debugging tomcat/jboss lighting talk
> - Any lighting talk based on spring guides https://spring.io/guides
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OJUG/OJUG/issues/4#issuecomment-131647947.

## 

-Juan

**Comment by mattdsteele** [comment]
Consolidated into `potential-topics.md`, feel free to edit/PR!
